export const Books=[
    {
        "book_id": 1,
        "book_img": "images/sekerportakali.jpg",
        "book_name": "Şeker Portakalı",
        "book_writer": "Jose Mauro De Vasconcelos",
        "book_price": "60",
        "book_type": "Dünya Roman",
    },
    {
        "book_id": 2,
        "book_img": "images/kürk.jpg",
        "book_name": "Kürk Mantolu Madonna",
        "book_writer": "Sabahattin Ali",
        "book_price": "35",
        "book_type": "Türk Roman",
    },
    {
        "book_id": 3,
        "book_img": "images/simyacı.jpg",
        "book_name": "Simyacı",
        "book_writer": "Paulo Coelho",
        "book_price": "65",
        "book_type": "Dünya Roman",
    },
    {
        "book_id": 4,
        "book_img": "images/sucveceza.jpg",
        "book_name": "Suç ve Ceza - Hasan Ali Yücel Klasikleri",
        "book_writer": " Fyodor Mihayloviç Dostoyevski",
        "book_price": "53",
        "book_type": "Dünya Klasik",
    },
    {
        "book_id": 5,
        "book_img": "images/beyazzambak.jpg",
        "book_name": "Beyaz Zambaklar Ülkesinde",
        "book_writer": "Grigory Petrov",
        "book_price": "18",
        "book_type": "Dünya Klasik",
    },
    {
        "book_id": 6,
        "book_img": "images/biridam.jpg",
        "book_name": "Bir İdam Mahkumunun Son Günü - Hasan Ali Yücel Klasikleri",
        "book_writer": "Victor Hugo",
        "book_price": "22",
        "book_type": "Dünya Klasik",
    },
    {
        "book_id": 7,
        "book_img": "images/itiraf.jpg",
        "book_name": "İtiraf",
        "book_writer": "İskender Pala",
        "book_price": "45",
        "book_type": "Türk Roman",
    },

]